### ISSUE TITLE
Bug: Deploy-stack doesnt wait for a successfull deployment before exiting with a 0 system code 

### ISSUE THREAD

**Issue by vickywane** [okteto/deploy-stack#8]
I am currently using the Deploy stack actions to deploy my application stack to an Okteto namespace within a GitHub Action workflow. 

After the stack is deployed, I have unit tests that make live HTTP tests against the deployed stack using the namespace URL. 
After several runs, I have discovered that the `deploy-stack` action **does not fully wait** for the deployment to be successful before exiting. This causes the action workflow to proceed to the next job which runs the API tests against **an unready** deployment. 

To augment, I have employed the use of the `nev7n/wait_for_response@v1` which waits for an extra 5s while pinging the deployment URL for a `200` status code to indicate a successful deployment. 

- Steps to reproduce: 
- Clone [this repository](https://github.com/vickywane/okteto-flask-app)
- Enable Github Actions and create a pull request to trigger the actions workflow. 

[Example](https://github.com/vickywane/okteto-flask-app/runs/3362602022?check_suite_focus=true) failing GitHub Action run without `nev7n/wait_for_response@v1`

[Example](https://github.com/vickywane/okteto-flask-app/runs/3367436839?check_suite_focus=true) passing GitHub Action run with`nev7n/wait_for_response@v1`

**Comment by pchico83** [comment]
@vickywane have you try with the `pipeline` action?
https://github.com/marketplace/actions/okteto-pipeline

**Comment by vickywane** [comment]
No. 

Would that be a better replacement for the `deploy-stack` action?

**Comment by pchico83** [comment]
@vickywane https://github.com/marketplace/actions/okteto-pipeline
The automatic pipeline will deploy your compose file:
https://okteto.com/docs/cloud/okteto-pipeline/#automatic-deployment

**Comment by rberrelleza** [comment]
closing since action is now deprecated
